name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  steamworks:
    path: ..

dev_dependencies:
  aeb_lint: ^1.1.0
