name: steamworks
description: Steamworks SDK wrapper written in a darty way to be used in dart projects
version: 0.4.7
homepage: https://github.com/aeb-dev/steamworks
repository: https://github.com/aeb-dev/steamworks
issues: https://github.com/aeb-dev/steamworks/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  logging: ^1.2.0

dev_dependencies:
  aeb_lint: ^1.1.0
  steamworks_gen: ^0.4.4
  test: ^1.24.5

platforms:
  linux:
  macos:
  windows:
