name: steamworks
description: Steamworks SDK wrapper written in a darty way to be used in dart projects
version: 0.2.1
homepage: https://github.com/aeb-dev/steamworks
repository: https://github.com/aeb-dev/steamworks
issues: https://github.com/aeb-dev/steamworks/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  ffi: ^1.2.0-dev.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  steamworks_gen: ^0.2.4

platforms:
  linux:
  macos:
  windows:
